spring:
   jmx:
      enabled: false
   application:
      name: Lego Imaging Application
   datasource:
      url: jdbc:mysql://shared50.accountservergroup.com:3306/a925261_dev_lego?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: a925261_legomgr
      password: g!oQf2W%TE2d!80xbo3i
      client-config-dir: C:\Users\tvatt\.credentials\site5\database
      client-config-file: site5-database-configuration.json
      database-key-name: site5-lego-dev
      hikari:
         connection-timeout: 123456
         idle-timeout: 98765
         connection-test-query: SELECT 1
         initialization-fail-timeout: 99999
         auto-commit: false
         login-timeout: 87654
         minimum-idle: 5
         maximum-pool-size: 25
         validation-timeout: 10000
         pool-name: site5-mysql-jdbc-pool

logging:
   level:
      root: DEBUG
      com.vattima.lego.data.ibatis.mapper: WARN
      net.bricklink.data: WARN
      org.springframework.jdbc: WARN
      org.mybatis: WARN
      com.gargoylesoftware: ERROR
      com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter: OFF
      com.zaxxer: DEBUG
      feign: DEBUG

bricklink:
   consumer:
      key: 9A62098F9A314327B0B8A28FFEF6A0EB
      secret: 72370639EE9D468CA3E8777E005BB320
   token:
      value: 07603FB14C474E2993BBF5AE4199C323
      secret: 6ED6C6275151480DA3541708FE5A5D59

lego:
   sheet:
      dataStoreDir: c:/users/tvatt/.credentials/sheets.googleapis.com-java-quickstart
      clientSecretDir: /client_secret.json
      id: 1KegFWxww3v6qWn6lfg8PWb-X8Ipc8Y3Asq7l6subgq4
      workbook: By BOX
      #workbook: By BOX, by NUMBER
      range: A2:F
   imaging:
      root-images-folder: C:/Users/tvatt/Desktop/lego-collection-photos
      root-inventory-items-folder: C:/Users/tvatt/Desktop/lego-collection-photos
      keywords-key-name: "Keywords:"

flickr:
   client-config-dir: C:\Users\tvatt\.credentials\flickr.api
   client-config-file: flickr-client-api-keys.json
   application-name: lego-imaging
   debug-request: false
   debug-stream: false

mybatis:
   type-aliases-package: com.vattima.lego.data.ibatis.type.aliases
   type-handlers-package: com.vattima.lego.data.ibatis.type.handler
   configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 1000
      default-statement-timeout: 30
      lazy-loading-enabled: true
   mapper-locations: com/vattima/lego/data/ibatis/*

debug: false
