package io.legohunter.imaging.model;

public enum PhotoServiceErrorType {
    ALBUM_NOT_FOUND,
    PHOTO_NOT_FOUND,
    PRIMARY_PHOTO_NOT_FOUND,
    AUTHENTICATION_FAILED,
    AUTHORIZATION_FAILED,
    INVALID_API_KEY,
    SERVICE_UNAVAILABLE,
    RATE_LIMITED,
    NETWORK_ERROR,
    WRITE_FAILED,
    VALIDATION_FAILED,
    EMPTY_PHOTO_LIST,
    DUPLICATE_UPLOAD,
    UPLOAD_LIMIT_EXCEEDED,
    FILE_TOO_LARGE,
    UNKNOWN
}
