package io.legohunter.imaging.service.sync.validation;

public enum SyncPreflightIssueType {
    ALBUM_REQUIRED,
    ALBUM_ID_REQUIRED,
    ALBUM_HAS_NO_PHOTOS,
    PHOTO_REQUIRED,
    PHOTO_FILE_MISSING,
    PHOTO_FILENAME_MISSING,
    PHOTO_ID_MISSING,
    PRIMARY_PHOTO_MISSING,
    PRIMARY_PHOTO_NOT_IN_MEMBERSHIP,
    MULTIPLE_PRIMARY_PHOTOS,
    DUPLICATE_PHOTO_ID,
    MEMBERSHIP_REQUIRED,
    MEMBERSHIP_HAS_NO_PHOTOS
}
