name: 'feature branch :: mvn deploy snapshot'
run-name: 'feature branch :: mvn deploy snapshot'
on:
  push:
    branches:
      - 'feature/**'
jobs:
  Feature-Branch-Maven-Deploy-Snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: mvn clean install
      run: mvn --batch-mode --update-snapshots deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}